server.port=${PORT:8080}

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,org.vaadin.example.bookstore

management.server.port=8082
management.endpoints.web.exposure.include=health,metrics,prometheus